def search(file_name: str, search_regex: str) -> list[(int, str)]:  ...
def search_dir(dir_path: str, search_regex: str) -> list[(int, str, str)]:  ...
def search_dir_ignore(dir_path: str, search_regex: str) -> list[(int, str, str)]:  ...
